DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/ViewComponents/FooterViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.Areas.Admin.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/ViewComponents/MainSidebarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.Areas.Admin.ViewComponents
{
    public class MainSidebarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/ViewComponents/NavbarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.Areas.Admin.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/ViewComponents/PreloaderViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.Areas.Admin.ViewComponents
{
    public class PreloaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Shared/_DataTablesCssPartial.cshtml
<!-- DataTables -->
<link rel="stylesheet" href="~/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">




@*
<!-- DataTables -->
<link rel="stylesheet" href="~/admin/plugins/datatables-bs4/~/ui/~/ui/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/admin/plugins/datatables-responsive/~/ui/~/ui/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/admin/plugins/datatables-buttons/~/ui/~/ui/css/buttons.bootstrap4.min.css">*@

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Shared/_DataTablesJsPartial.cshtml
<!-- DataTables  & Plugins -->
<script src="~/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/admin/plugins/jszip/jszip.min.js"></script>
<script src="~/admin/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/admin/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>


@*<!-- DataTables  & Plugins -->
<script src="~/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/admin/plugins/datatables-bs4/~/ui/~/ui/js/dataTables.bootstrap4.min.js"></script>
<script src="~/admin/plugins/datatables-responsive/~/ui/~/ui/js/dataTables.responsive.min.js"></script>
<script src="~/admin/plugins/datatables-responsive/~/ui/~/ui/js/responsive.bootstrap4.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/~/ui/~/ui/js/dataTables.buttons.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/~/ui/~/ui/js/buttons.bootstrap4.min.js"></script>
<script src="~/admin/plugins/jszip/jszip.min.js"></script>
<script src="~/admin/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/admin/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/admin/plugins/datatables-buttons/~/ui/~/ui/js/buttons.html5.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/~/ui/~/ui/js/buttons.print.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/~/ui/~/ui/js/buttons.colVis.min.js"></script>*@
<script>
    $(function () {
        $("#myDataTable").DataTable({
            "responsive": true,
            "lengthChange": true,
            "autoWidth": false,
            "buttons": ["copy", "excel", "pdf", "print"],
            "language": {
                "info": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
                "infoEmpty": "Kayıt yok",
                "infoFiltered": "(_MAX_ kayıt içerisinden bulunan)",
                "infoThousands": ".",
                "lengthMenu": "Her sayfada _MENU_ kayıt göster",
                "loadingRecords": "Yükleniyor...",
                "processing": "İşleniyor...",
                "search": "Ara:",
                "zeroRecords": "Aradığınız kayıt bulunamadı",
                "paginate": {
                    "first": "İlk",
                    "last": "Son",
                    "next": "Sonraki",
                    "previous": "Önceki"
                },
                "aria": {
                    "sortAscending": ": artan sütun sıralamasını aktifleştir",
                    "sortDescending": ": azalan sütun sıralamasını aktifleştir"
                },
                "select": {
                    "rows": {
                        "1": "1 kayıt seçildi",
                        "_": "%d kayıt seçildi"
                    },
                    "cells": {
                        "1": "1 hücre seçildi",
                        "_": "%d hücre seçildi"
                    },
                    "columns": {
                        "1": "1 sütun seçildi",
                        "_": "%d sütun seçildi"
                    }
                },
                "autoFill": {
                    "cancel": "İptal",
                    "fillHorizontal": "Hücreleri yatay olarak doldur",
                    "fillVertical": "Hücreleri dikey olarak doldur",
                    "fill": "Bütün hücreleri <i>%d</i> ile doldur",
                    "info": "Detayı"
                },
                "buttons": {
                    "collection": "Koleksiyon <span class=\"ui-button-icon-primary ui-icon ui-icon-triangle-1-s\"></span>",
                    "colvis": "Sütun görünürlüğü",
                    "colvisRestore": "Görünürlüğü eski haline getir",
                    "copySuccess": {
                        "1": "1 satır panoya kopyalandı",
                        "_": "%ds satır panoya kopyalandı"
                    },
                    "copyTitle": "Panoya kopyala",
                    "csv": "CSV",
                    "excel": "Excel",
                    "pageLength": {
                        "1": "1 Satır Göster",
                        "-1": "Bütün satırları göster",
                        "_": "%d satır göster"
                    },
                    "pdf": "PDF",
                    "print": "Yazdır",
                    "copy": "Kopyala",
                    "copyKeys": "Tablodaki veriyi kopyalamak için CTRL veya u2318 + C tuşlarına basınız. İptal etmek için bu mesaja tıklayın veya escape tuşuna basın.",
                    "createState": "Şuanki Görünümü Kaydet",
                    "removeAllStates": "Tüm Görünümleri Sil",
                    "removeState": "Aktif Görünümü Sil",
                    "renameState": "Aktif Görünümün Adını Değiştir",
                    "savedStates": "Kaydedilmiş Görünümler",
                    "stateRestore": "Görünüm -&gt; %d",
                    "updateState": "Aktif Görünümün Güncelle"
                },
                "searchBuilder": {
                    "add": "Koşul Ekle",
                    "button": {
                        "0": "Arama Oluşturucu",
                        "_": "Arama Oluşturucu (%d)"
                    },
                    "condition": "Koşul",
                    "conditions": {
                        "date": {
                            "after": "Sonra",
                            "before": "Önce",
                            "between": "Arasında",
                            "empty": "Boş",
                            "equals": "Eşittir",
                            "not": "Değildir",
                            "notBetween": "Dışında",
                            "notEmpty": "Dolu"
                        },
                        "number": {
                            "between": "Arasında",
                            "empty": "Boş",
                            "equals": "Eşittir",
                            "gt": "Büyüktür",
                            "gte": "Büyük eşittir",
                            "lt": "Küçüktür",
                            "lte": "Küçük eşittir",
                            "not": "Değildir",
                            "notBetween": "Dışında",
                            "notEmpty": "Dolu"
                        },
                        "string": {
                            "contains": "İçerir",
                            "empty": "Boş",
                            "endsWith": "İle biter",
                            "equals": "Eşittir",
                            "not": "Değildir",
                            "notEmpty": "Dolu",
                            "startsWith": "İle başlar",
                            "notContains": "İçermeyen",
                            "notStartsWith": "Başlamayan",
                            "notEndsWith": "Bitmeyen"
                        },
                        "array": {
                            "contains": "İçerir",
                            "empty": "Boş",
                            "equals": "Eşittir",
                            "not": "Değildir",
                            "notEmpty": "Dolu",
                            "without": "Hariç"
                        }
                    },
                    "data": "Veri",
                    "deleteTitle": "Filtreleme kuralını silin",
                    "leftTitle": "Kriteri dışarı çıkart",
                    "logicAnd": "ve",
                    "logicOr": "veya",
                    "rightTitle": "Kriteri içeri al",
                    "title": {
                        "0": "Arama Oluşturucu",
                        "_": "Arama Oluşturucu (%d)"
                    },
                    "value": "Değer",
                    "clearAll": "Filtreleri Temizle"
                },
                "searchPanes": {
                    "clearMessage": "Hepsini Temizle",
                    "collapse": {
                        "0": "Arama Bölmesi",
                        "_": "Arama Bölmesi (%d)"
                    },
                    "count": "{total}",
                    "countFiltered": "{shown}/{total}",
                    "emptyPanes": "Arama Bölmesi yok",
                    "loadMessage": "Arama Bölmeleri yükleniyor ...",
                    "title": "Etkin filtreler - %d",
                    "showMessage": "Tümünü Göster",
                    "collapseMessage": "Tümünü Gizle"
                },
                "thousands": ".",
                "datetime": {
                    "amPm": [
                        "öö",
                        "ös"
                    ],
                    "hours": "Saat",
                    "minutes": "Dakika",
                    "next": "Sonraki",
                    "previous": "Önceki",
                    "seconds": "Saniye",
                    "unknown": "Bilinmeyen",
                    "weekdays": {
                        "0": "Pzt",
                        "1": "Sal",
                        "2": "Çar",
                        "3": "Per",
                        "4": "Cum",
                        "5": "Cmt",
                        "6": "Paz"
                    },
                    "months": {
                        "0": "Ocak",
                        "1": "Şubat",
                        "2": "Mart",
                        "3": "Nisan",
                        "4": "Mayıs",
                        "5": "Haziran",
                        "6": "Temmuz",
                        "7": "Ağustos",
                        "8": "Eylül",
                        "9": "Ekim",
                        "10": "Kasım",
                        "11": "Aralık"
                    }
                },
                "decimal": ",",
                "editor": {
                    "close": "Kapat",
                    "create": {
                        "button": "Yeni",
                        "submit": "Kaydet",
                        "title": "Yeni kayıt oluştur"
                    },
                    "edit": {
                        "button": "Düzenle",
                        "submit": "Güncelle",
                        "title": "Kaydı düzenle"
                    },
                    "error": {
                        "system": "Bir sistem hatası oluştu (Ayrıntılı bilgi)"
                    },
                    "multi": {
                        "info": "Seçili kayıtlar bu alanda farklı değerler içeriyor. Seçili kayıtların hepsinde bu alana aynı değeri atamak için buraya tıklayın; aksi halde her kayıt bu alanda kendi değerini koruyacak.",
                        "noMulti": "Bu alan bir grup olarak değil ancak tekil olarak düzenlenebilir.",
                        "restore": "Değişiklikleri geri al",
                        "title": "Çoklu değer"
                    },
                    "remove": {
                        "button": "Sil",
                        "confirm": {
                            "1": "Bu kaydı silmek istediğinizden emin misiniz?",
                            "_": "%d adet kaydı silmek istediğinize emin misiniz?"
                        },
                        "submit": "Sil",
                        "title": "Kayıtları sil"
                    }
                },
                "stateRestore": {
                    "creationModal": {
                        "button": "Kaydet",
                        "columns": {
                            "search": "Kolon Araması",
                            "visible": "Kolon Görünümü"
                        },
                        "name": "Görünüm İsmi",
                        "order": "Sıralama",
                        "paging": "Sayfalama",
                        "scroller": "Kaydırma (Scrool)",
                        "search": "Arama",
                        "searchBuilder": "Arama Oluşturucu",
                        "select": "Seçimler",
                        "title": "Yeni Görünüm Oluştur",
                        "toggleLabel": "Kaydedilecek Olanlar"
                    },
                    "duplicateError": "Bu Görünüm Daha Önce Tanımlanmış",
                    "emptyError": "Görünüm Boş Olamaz",
                    "emptyStates": "Herhangi Bir Görünüm Yok",
                    "removeJoiner": "ve",
                    "removeSubmit": "Sil",
                    "removeTitle": "Görünüm Sil",
                    "renameButton": "Değiştir",
                    "renameLabel": "Görünüme Yeni İsim Ver -&gt; %s:",
                    "renameTitle": "Görünüm İsmini Değiştir",
                    "removeConfirm": "Görünümü silmek istediğinize emin misiniz?",
                    "removeError": "Görünüm silinemedi"
                },
                "emptyTable": "Tabloda veri bulunmuyor",
                // "infoPostFix": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
                "searchPlaceholder": "Ara..."
            }

        }).buttons().container().appenViewModel('#myDataTable_wrapper .col-md-6:eq(0)');
    });
</script>

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>
    @await Html.PartialAsync("_Styles")
    @await RenderSectionAsync("Styles", false)
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        @await Component.InvokeAsync("Preloader")
        @await Component.InvokeAsync("Navbar")
        @await Component.InvokeAsync("MainSidebar")
        @RenderBody()
        @await Component.InvokeAsync("Footer")
    </div>
    <!-- ./wrapper -->
    @await Html.PartialAsync("_Scripts")
    @await RenderSectionAsync("Scripts", false)
</body>

</html>

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Shared/_Scripts.cshtml
<!-- jQuery -->
<script src="~/admin/plugins/jquery/jquery.min.js"></script>

<!-- Bootstrap 4 -->
<script src="~/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- overlayScrollbars -->
<script src="~/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

<!-- AdminLTE App -->
<script src="~/admin/dist/js/adminlte.js"></script>




@*<!-- jQuery -->
<script src="~/admin/plugins/jquery/jquery.min.js"></script>

<!-- Bootstrap 4 -->
<script src="~/admin/plugins/bootstrap/~/ui/~/ui/js/bootstrap.bundle.min.js"></script>

<!-- overlayScrollbars -->
<script src="~/admin/plugins/overlayScrollbars/~/ui/~/ui/js/jquery.overlayScrollbars.min.js"></script>

<!-- AdminLTE App -->
<script src="~/admin/dist/~/ui/~/ui/js/adminlte.js"></script>*@

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Shared/_Styles.cshtml
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<!-- Font Awesome -->
<link rel="stylesheet" href="~/admin/plugins/fontawesome-free/css/all.min.css">

<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/~/ui/~/ui/css/ionicons.min.css">

<!-- Theme style -->
<link rel="stylesheet" href="~/admin/dist/css/adminlte.min.css">

<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">




@*<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<!-- Font Awesome -->
<link rel="stylesheet" href="~/admin/plugins/fontawesome-free/~/ui/~/ui/css/all.min.css">

<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/~/ui/~/ui/css/ionicons.min.css">

<!-- Theme style -->
<link rel="stylesheet" href="~/admin/dist/~/ui/~/ui/css/adminlte.min.css">

<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/admin/plugins/overlayScrollbars/~/ui/~/ui/css/OverlayScrollbars.min.css">*@

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Shared/_SummerNotePartial.cshtml
    <!-- Summernote -->
    <script src="~/admin/plugins/summernote/summernote-bs4.min.js"></script>
    <script>
        $('#Properties').summernote({
            height: 200
        })
    </script>