DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Controllers/RoleController.cs
using DegerliMadenSatis.Entity.Concrete.identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DegerliMadenSatis.MVC.Areas.Admin.Controllers
{
    
        [Authorize(Roles = "SuperAdmin")]
        [Area("Admin")]
        public class RoleController : Controller
        {
            private readonly UserManager<User> _userManager;
            private readonly RoleManager<Role> _roleManager;


            public RoleController(UserManager<User> userManager, RoleManager<Role> roleManager)
            {
                _userManager = userManager;
                _roleManager = roleManager;
            }
         
            public async Task<IActionResult> Index() => View(await _roleManager.Roles.ToListAsync()); //2. Yöntem kullanıcı listeleme.
        }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Areas/Admin/Views/Role/Index.cshtml
@*Rol Listeleme*@
@model List<Role>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="d-flex justify-content-between mb-2">
                <div>
                    <h1>Rol Listesi</h1>
                </div>
                <div>
                    <a asp-area="Admin"
                       asp-controller="Role"
                       asp-action="Create"
                       class="btn btn-success btn-sm">Yeni Rol</a>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="myDataTable" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Rol Adı</th>
                                        <th>Açıklama</th>
                                        <th width="55">#</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var r in Model)
                                    {
                                        <tr>
                                            <td>@r.Id</td>
                                            <td>@r.Name </td>
                                            <td>@r.Description</td>
                                            <td class="text-center">

                                                <a asp-area="Admin"
                                               asp-controller="Role"
                                               asp-action="AssigUsers"
                                               asp-route-id="@r.Id"
                                               class="btn btn-warning btn-sm">
                                                    <i class="far fa-edit"></i>
                                                </a>
                                                <a asp-area="Admin"
                                               asp-controller="Role"
                                               asp-action="Delete"
                                               asp-route-id="@r.Id"
                                               class="btn btn-danger btn-sm">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section Styles{
    @await Html.PartialAsync("_DataTablesCssPartial")
}

@section Scripts{
    @await Html.PartialAsync("_DataTablesJsPartial")
}