DegerliMadenSatiss/DegerliMadenSatis.Mvc/Controllers/ProductController.cs
using DegerliMadenSatis.Business.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productManager;
        private readonly ICategoryService _categoryManager;

        public ProductController(IProductService productManager, ICategoryService categoryManager)
        {
            _productManager = productManager;
            _categoryManager = categoryManager;
        }

        public async Task<IActionResult> Index(int? id=null)
        {
            var products = id == null ?
                await _productManager.GetAllNonDeletedAsync() :
                await _productManager.GetProductsByCategoryIdAsync(Convert.ToInt32(id));
            var category = id != null ? await _categoryManager.GetByIdAsync(Convert.ToInt32(id)) : null;
            ViewBag.CategoryName = category.Data != null ? category.Data.Name : null; 
            return View(products.Data);
        }

        /*[Authorize]*///Sadece login olanlar detay sayfasını görecek.
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productManager.GetByIdAsync(id);
            return View(product.Data);
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Controllers/ShoppingCartController.cs
using DegerliMadenSatis.Business.Abstract;
using DegerliMadenSatis.Entity.Concrete.identity;
using DegerliMadenSatis.Shared.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IShoppingCartService _shoppingCartManager;
        private readonly IShoppingCartItemService _shoppingCartItemManager;


        public ShoppingCartController(UserManager<User> userManager, IShoppingCartService shoppingCartManager, IShoppingCartItemService shoppingCartItemManager)
        {
            _userManager = userManager;
            _shoppingCartManager = shoppingCartManager;
            _shoppingCartItemManager = shoppingCartItemManager;
        }

        //Kullanıcının sepeti.
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User); //O an login olan kullanıcının bana Id sini ver.
            var shoppingcart = await _shoppingCartManager.GetShoppingCartByUserIdAsync(userId); //shoppingCart ı getirdi.

            return View(shoppingcart.Data);
        }
        public async Task<IActionResult> AddToCart(int productId, int quantity = 1)
        {
            var userId = _userManager.GetUserId(User);
            await _shoppingCartManager.AddToCartAsync(userId,productId,quantity);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangeQuantity(ShoppingCartItemViewModel shoppingCartItemViewModel)
        {
            if (ModelState.IsValid)
            {
                await _shoppingCartItemManager.ChangeQuantityAsync(shoppingCartItemViewModel.Id, shoppingCartItemViewModel.Quantity);
                return RedirectToAction("Index");
            }
            return View(shoppingCartItemViewModel);
        }
        
        public async Task<IActionResult> DeleteItem(int id)
        {
            await _shoppingCartItemManager.DeleteFromShoppingCartAsync(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ClearCart(int id)
        {
            await _shoppingCartItemManager.ClearShoppingCartAsync(id);
            return RedirectToAction("Index");
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/ViewComponents/CategoriesViewComponent.cs
using DegerliMadenSatis.Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace DegerliMadenSatis.MVC.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private readonly ICategoryService _categoryManager;

        public CategoriesViewComponent(ICategoryService categoryManager)
        {
            _categoryManager = categoryManager;
        }

        public async Task<IViewComponentResult> InvokeAsync() 
        {
            var response = await _categoryManager.GetTopCategories(5);
            return View(response.Data);
        }
    }
}

DegerliMadenSatiss/DegerliMadenSatis.Mvc/Views/Home/Index.cshtml
@model List<ProductViewModel>
@await Component.InvokeAsync("Categories")

<!--MVC>Views>Shared>Components>Categories>Default içinde kodlar.-->
<!--Sepet için ürün listeleme büyük menu altı-->
<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">        
        <!-- Services Section Begin -->
        <section class="services spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <i class="fa fa-car"></i>
                            <h6>Ücretsiz Kargo</h6>
                            <p>Tüm Ürünlerde Ücretsiz Kargo Fırsatı</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <i class="fa fa-money"></i>
                            <h6>Rekabetçi Fiyat</h6>
                            <p>En Uygun Fiyat Garantisi</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <i class="fa fa-support"></i>
                            <h6>24/7 Anında Destek</h6>
                            <p>1 dk. Altında Erişim</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <i class="fa fa-headphones"></i>
                            <h6>Güvenli Ödeme</h6>
                            <p>100% güvenli ödeme</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        <!-- Services Section End -->
        <div class="row">
            <div class="col-lg-4 col-md-4">
                <div class="section-title">
                    <h4>Tüm Ürünler</h4>
                </div>
            </div>            
        </div>

        <div class="row property__gallery">
            @foreach (var p in Model)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 mix women">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg="/images/products/@p.ImageUrl">
                            <a asp-area="" asp-controller="Product" asp-action="Details" asp-route-id="@p.Id" class="label new">Detay</a>
                            <ul class="product__hover">
                                <li><a href="/images/products/@p.ImageUrl" class="image-popup"><span class="arrow_expand"></span></a></li>
                            <li><a href="#"><span class="icon_heart_alt"></span></a></li>
                            <li>
                                <form 
                                    asp-area="" 
                                    asp-controller="ShoppingCart" 
                                    asp-action="AddToCart"                                    
                                >
                                    <input type="hidden" name="productId" value="@p.Id" />
                                    <input type="hidden" name="quantity" value="1" />                                    
                                    <button type="submit" style="background-color:transparent; border:none"><a><span class="icon_bag_alt"></span></a></button>
                                </form>
                            </li>
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6><a href="#">@p.Name</a></h6>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <div class="product__price">@($"{p.Price:C0}")</div>
                    </div>
                </div>
            </div>   
            }
            
        </div>
    </div>
</section>
<!-- Product Section End -->

@*<!-- Banner Section Begin -->
<section class="banner set-bg">
    <div class="container">
        <div class="row">
            <div class="col-xl-7 col-lg-8 m-auto">
                <div class="banner__slider owl-carousel">
                    <div class="banner__item">
                        <div class="banner__text">
                            <span>Altın Rekor Kırdı</span>
                            <h1>The Project Jacket</h1>
                            <a href="#">Shop now</a>
                        </div>
                    </div>
                    <div class="banner__item">
                        <div class="banner__text">
                            <span>The Chloe Collection</span>
                            <h1>The Project Jacket</h1>
                            <a href="#">Shop now</a>
                        </div>
                    </div>
                    <div class="banner__item">
                        <div class="banner__text">
                            <span>The Chloe Collection</span>
                            <h1>The Project Jacket</h1>
                            <a href="#">Shop now</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section End -->*@

<!-- Instagram Begin -->

<div class="instagram">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="/images/brands/fed.png">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="/images/brands/mb.png">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="/images/brands/spk.png">
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="/images/brands/bddk.png">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="/images/brands/bist.png">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="/images/brands/iar.png">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#"></a>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
<!-- Instagram End -->